--- POSTGRESQL 10 ONLY!!!

CREATE TABLE aidb.locations (
    loc_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    issued_on        date NOT NULL DEFAULT now()
);

CREATE TABLE aidb.physical_locations (
    loc_description TEXT,
    country  INTEGER REFERENCES aidb.country (id),
    town TEXT,
    street TEXT,
    zipcode TEXT
) INHERITS (locations);

CREATE TABLE aidb.virtual_locations (
    department_id    text NOT NULL
) INHERITS (locations);